#!/bin/bash

NTEX=`ls ./*.tex | wc -l`
if [ $NTEX -eq 1 ]; then
    FILE=`ls|grep tex`
    PROCEED=1
else
    echo "Found $NTEX tex files"
    PROCEED=0
    for ((f=1;f<=${NTEX};f++)); do
        FILE=`ls|grep tex|head -n $f|tail -n 1`
        if [ "$FILE" == "$1" ]; then
           PROCEED=1
           break
        fi
        echo "You did not explicitly choose $FILE.."
    done
    echo "You chose nothing, let's try again.."
    if [ $PROCEED == 0 ]; then
        for ((f=1;f<=${NTEX};f++)); do
            FILE=`ls|grep tex|head -n $f|tail -n 1`
            read -p "Is it $FILE? [yn]  "
            if [ "$REPLY" == "y" ]; then
               PROCEED=1
               break
            fi
        done
    fi
fi

if [ $PROCEED == 1 ]; then
    NAME=`echo $FILE | cut -d '.' -f 1`
    echo "Processing $FILE.. ($NAME)"
    #rm -v ${name}.{aux,blg,bbl}
    pdflatex $FILE
    pdflatex $FILE
    evince $NAME.pdf&
else
    echo "Nothing to do"
    echo "Exit"
fi
